name: dart_secrets_scanner
description: command-line tool designed to scan Dart and related files in Flutter projects for hardcoded sensitive information such as API keys, tokens, passwords, and other credentials.
version: 1.0.2
homepage: https://github.com/Wreos/dart_secrets_scanner

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
